### ISSUE TITLE
No Module named shuup.api

### ISSUE THREAD

**Issue by lucasitz** [chessbr/shuup-project-template#1]
When i run migrate returns the error:
python manage.py migrate
Traceback (most recent call last):
  File "/home/lucas/projetos/shuup-project-template/env/lib/python3.6/site-packages/django/apps/config.py", line 122, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'shuup' has no attribute 'api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lucas/projetos/shuup-project-template/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/lucas/projetos/shuup-project-template/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/lucas/projetos/shuup-project-template/env/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/lucas/projetos/shuup-project-template/env/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/lucas/projetos/shuup-project-template/env/lib/python3.6/site-packages/django/apps/config.py", line 127, in create
    import_module(entry)
  File "/home/lucas/projetos/shuup-project-template/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'shuup.api'

I've started shuup app before with no problems, and after try this template and return this error.. sry my bad english

**Comment by chessbr** [comment]
Hi @lucasitz !
I've just fixed the issue. Shuup 1.10 created some breaking changes https://github.com/shuup/shuup/releases/tag/v1.10.0

Thanks
